version: "3.9"

services:
  mysql:
    image: mysql:latest
    ports: 
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3
      - MYSQL_DATABASE=crud
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: unless-stopped
  frontend:
    container_name: frontend-crud
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    network_mode: host
    restart: unless-stopped
  backend:
    container_name: backend-crud
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    network_mode: host
    restart: unless-stopped